AllCops:
  RunRailsCops: true
  Exclude:
    - 'gakubuchi.gemspec'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/dummy/**/*'

Documentation:
  Enabled: false

LineLength:
  Max: 100
